# Generated by Django 4.2.29 on 2026-04-02 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('image', models.URLField(blank=True, verbose_name='Изображение')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Дата выхода')),
                ('lte_exists', models.BooleanField(default=False, verbose_name='Поддержка LTE')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Телефон',
                'verbose_name_plural': 'Телефоны',
                'ordering': ['name'],
            },
        ),
    ]
